### PR TITLE
Aiohttp 3.6.2 plus connection leak fix

### PR DESCRIPTION
**Pull request by pfreixes**
Upgrades to the last stable version of Aiohttp - 3.6.2 tag - plus adds a hotfix which is pending to be reviewed [1] that fixes a bug with a race condition that might leak connections in the client connection pool under some circumstances.

Tests pass in local:

```bash
$ make test
============================================================================= 2458 passed, 16 skipped, 3 xfailed in 131.33s (0:02:11) =============================================================================
```

[1] https://github.com/aio-libs/aiohttp/pull/4562

### CODE REVIEW

**Comment by pfreixes** [comment]
@vangheem and @lferran seem that new version does not break onna canonica [1], so if you agree the steps that would need to be done will be:

1) Create a new version of the forked version of Aiohttp (I would need some help from @vangheem for uploading it to our pypi)
2) Updraft the PR [1] https://github.com/atlasense/onna-canonical/pull/4218 and change the requirement for using the one that we published
3) Nothing else


[1] https://jenkins.atlasense.com/blue/organizations/jenkins/platform%2Fonna-canonical/detail/bump-aiohttp-version/1/pipeline

**Comment by vangheem** [comment]
@pfreixes do we need to re-fork? I notice that we have a lot of conflicts.

**Comment by vangheem** [comment]
Also, do we need to keep forking at this point?

**Comment by vangheem** [comment]
https://github.com/aio-libs/aiohttp/pull/4562/files is the cherry-picked additional fix

**Review by vangheem — APPROVED** [review]

**Comment by pfreixes** [comment]
As we speak I will override the master branch with this

**Pull request merged**
